//https://www.techonthenet.com/js/language_tags.php
//https://learn.microsoft.com/en-us/azure/cognitive-services/speech-service/language-support?tabs=stt
export const LanguageTags = [
  { value: 'ar-SA', description: 'Arabic' },
  { value: 'bn-BD', description: 'Bangla' },
  { value: 'bn-IN', description: 'Bangla (India)' },
  { value: 'cs-CZ', description: 'Czech' },
  { value: 'da-DK', description: 'Danish' },
  { value: 'de-AT', description: 'German (Austria)' },
  { value: 'de-CH', description: 'German (Switzerland)' },
  { value: 'de-DE', description: 'German' },
  { value: 'el-GR', description: 'Greek' },
  { value: 'en-AU', description: 'English (Australia)' },
  { value: 'en-CA', description: 'English (Canada)' },
  { value: 'en-GB', description: 'English (UK)' },
  { value: 'en-IE', description: 'English (Ireland)' },
  { value: 'en-IN', description: 'English (India)' },
  { value: 'en-NZ', description: 'English (New Zealand)' },
  { value: 'en-US', description: 'English (US)' },
  { value: 'en-ZA', description: 'English (South Africa)' },
  { value: 'es-AR', description: 'Spanish (Argentina)' },
  { value: 'es-CL', description: 'Spanish (Chile)' },
  { value: 'es-CO', description: 'Spanish (Columbia)' },
  { value: 'es-ES', description: 'Spanish' },
  { value: 'es-MX', description: 'Spanish (Mexico)' },
  { value: 'es-US', description: 'Spanish (US)' },
  { value: 'fi-FI', description: 'Finnish' },
  { value: 'fr-BE', description: 'French (Belgium)' },
  { value: 'fr-CA', description: 'French (Canada)' },
  { value: 'fr-CH', description: 'French (Switzerland)' },
  { value: 'fr-FR', description: 'French' },
  { value: 'he-IL', description: 'Hebrew' },
  { value: 'hi-IN', description: 'Hindi' },
  { value: 'hu-HU', description: 'Hungarian' },
  { value: 'id-ID', description: 'Indonesian' },
  { value: 'it-CH', description: 'Italian (Switzerland)' },
  { value: 'it-IT', description: 'Italian' },
  { value: 'ja-JP', description: 'Japanese' },
  { value: 'ko-KR', description: 'Korea' },
  { value: 'nl-BE', description: 'Dutch (Belgium)' },
  { value: 'nl-NL', description: 'Dutch' },
  { value: 'no-NO', description: 'Norwegian' },
  { value: 'pl-PL', description: 'Polish' },
  { value: 'pt-BR', description: 'Portugese (Brazil)' },
  { value: 'pt-PT', description: 'Portugese' },
  { value: 'ro-RO', description: 'Romanian' },
  { value: 'ru-RU', description: 'Russian' },
  { value: 'sk-SK', description: 'Slovak' },
  { value: 'sv-SE', description: 'Swedish' },
  { value: 'ta-IN', description: 'Tamil (India)' },
  { value: 'ta-LK', description: 'Tamil (Sri Lanka)' },
  { value: 'th-TH', description: 'Thai' },
  { value: 'tr-TR', description: 'Turkish' },
  { value: 'vi-VN', description: 'Vietnamese' },
  { value: 'zh-CN', description: 'Chinese (Mandarin, Simplified)' },
  { value: 'zh-HK', description: 'Chinese (Cantonese, Traditional)' },
  { value: 'zh-TW', description: 'Taiwanese (Mandarin, Traditional)' },
];