//https://learn.microsoft.com/en-us/azure/cognitive-services/speech-service/language-support?tabs=stt
//Local (BCP-47), Audio + human-labeled transcript only
export const LanguageTags = [
  { value: 'ar-BH', description: 'Arabic (Bahrain)' },
  { value: 'ar-DZ', description: 'Arabic (Algeria)' },
  { value: 'ar-EG', description: 'Arabic (Egypt)' },
  { value: 'ar-MA', description: 'Arabic (Morocco)' },
  { value: 'ar-SA', description: 'Arabic (Saudi Arabia)' },
  { value: 'ar-TN', description: 'Arabic (Tunisia)' },
  { value: 'ar-YE', description: 'Arabic (Yemen)' },
  { value: 'cs-CZ', description: 'Czech (Czechia)' },
  { value: 'da-DK', description: 'Danish (Denmark)' },
  { value: 'de-AT', description: 'German (Austria)' },
  { value: 'de-CH', description: 'German (Switzerland)' },
  { value: 'de-DE', description: 'German (Germany)' },
  { value: 'en-AU', description: 'English (Australia)' },
  { value: 'en-CA', description: 'English (Canada)' },
  { value: 'en-GB', description: 'English (UK)' },
  { value: 'en-GH', description: 'English (Ghana)' },
  { value: 'en-HK', description: 'English (HK SAR)' },
  { value: 'en-IE', description: 'English (Ireland)' },
  { value: 'en-IN', description: 'English (India)' },
  { value: 'en-KE', description: 'English (Kenya)' },
  { value: 'en-NG', description: 'English (Nigeria)' },
  { value: 'en-NZ', description: 'English (New Zealand)' },
  { value: 'en-PH', description: 'English (Philippines)' },
  { value: 'en-SG', description: 'English (Singapore)' },
  { value: 'en-TZ', description: 'English (Tanzania)' },
  { value: 'en-US', description: 'English (US)' },
  { value: 'en-ZA', description: 'English (South Africa)' },
  { value: 'es-ES', description: 'Spanish (Spain)' },
  { value: 'es-MX', description: 'Spanish (Mexico)' },
  { value: 'fil-PH', description: 'Filipino (Philippines)' },
  { value: 'fr-BE', description: 'French (Belgium)' },
  { value: 'fr-CA', description: 'French (Canada)' },
  { value: 'fr-FR', description: 'French (France)' },
  { value: 'hi-IN', description: 'Hindi (India)' },
  { value: 'hu-HU', description: 'Hungarian (Hungary)' },
  { value: 'it-CH', description: 'Italian (Switzerland)' },
  { value: 'it-IT', description: 'Italian (Italy)' },
  { value: 'ja-JP', description: 'Japanese (Japan)' },
  { value: 'ko-KR', description: 'Korean (Korea)' },
  { value: 'ms-MY', description: 'Malay (Malaysia)' },
  { value: 'nb-NO', description: 'Norwegian Bokmål (Norway)' },
  { value: 'nl-NL', description: 'Dutch (Netherlands)' },
  { value: 'pl-PL', description: 'Polish (Poland)' },
  { value: 'pt-BR', description: 'Portugese (Brazil)' },
  { value: 'pt-PT', description: 'Portugese (Portugal)' },
  { value: 'ru-RU', description: 'Russian (Russia)' },
  { value: 'sv-SE', description: 'Swedish (Sweden)' },
  { value: 'th-TH', description: 'Thai (Thailand)' },
  { value: 'tr-TR', description: 'Turkish (Turkey)' },
  { value: 'vi-VN', description: 'Vietnamese (Vietnam)' },
  { value: 'wuu-CN', description: 'Chinese (Wu, Simplified)' },
  { value: 'yue-CN', description: 'Chinese (Cantonese, Simplified)' },
  { value: 'zh-CN', description: 'Chinese (Mandarin, Simplified)' },
  { value: 'zh-CN-shandong', description: 'Chinese (Jilu Mandarin, Simplified)' },
  { value: 'zh-CN-sichuan', description: 'Chinese (SW Mandarin, Simplified)' },
  { value: 'zh-HK', description: 'Chinese (Cantonese, Traditional)' },
  { value: 'zh-TW', description: 'Chinese (Taiwanese Mandarin, Traditional)' },
];